[project]
name = "uvproj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ccxt>=4.4.94",
    "plotly>=5.22.0",
    "pysocks>=1.7.1",
    "dash>=2.0.0",
    "pandas>=2.3.1",
    "dash-bootstrap-components>=1.0.0",
]
