[project]
name = "uvproj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ccxt>=4.4.94",
    "matplotlib>=3.10.3",
    "pandas>=2.3.1",
    "pysocks>=1.7.1",
]
